server:
  port: 8080

spring:
  application:
    name: EventsNotificator

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: localhost
    port: 1025
    username: no-reply@events-notificator.com
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

notifications:
#  cron: 0 0 9 * * *
  cron: 0 */3 * * * *